# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ source ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 12.x ]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: git submodule init
    - run: git submodule update
    - run: rm -fr public/
    - run: |
        git fetch origin master
        git worktree add -B master public origin/master
    - run: npx hexo generate
    - run: |
        cd public
        git add .
        git commit -m "Update master"
        git config --global user.name 'GitHub Action'
        git config --global user.email 'ruiruibupt@gmail.com'
        git push
